### PR TITLE
Fix porblem with method 'first'. Method 'first' adds 'ORDER BY id'

### PR DESCRIPTION
**Pull request by kelevro**
Fix porblem with method 'first'. Method 'first' adds 'ORDER BY id'

### CODE REVIEW

**Comment by drinks** [comment]
Hi and thanks for the PR! Could you expand a little on what problem this addresses? To be clear, the code in question does not return model instances, but rather uses the AR relation as a shell connection to retrieve exactly one row of aggregate information. In this circumstance, it should not be important what order is associated with the query--its resulting SQL is not that which is used to create the query hash.

If I'm missing something relevant, please let me know, and thanks again!

**Comment by kelevro** [comment]
Hi and thanks for the nice gem. When You call `Manager.first`, you have sql like `SELECT  "managers".* FROM "managers"  ORDER BY "managers"."id" ASC LIMIT 1`. Call `Manager.collection_cache_key` throw exception `ActiveRecord::StatementInvalid: PG::GroupingError: ERROR:  column "managers.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...timestamp FROM "managers" WHERE (1 = 1)  ORDER BY "managers"...` because generated sql is `SELECT  COUNT(*) AS size, MAX("managers"."updated_at") AS timestamp FROM "managers" WHERE (1 = 1)  ORDER BY "managers"."id" ASC LIMIT 1`.

**Comment by drinks** [comment]
Ah, got it -- Seems the issue only occurs when using the PG adapter. Your patch looks fine to me, I'll merge and publish today.

**Comment by kelevro** [comment]
Ok. Thanks.

**Comment by drinks** [comment]
Thanks again for the patch! This has been published in v0.1.2

**Pull request merged**
